### ISSUE TITLE
Generic Request is 400 Bad Request

### ISSUE THREAD

**Issue by rquanx** [koltyakov/sp-rest-proxy#76]
I want to use JSOM in local but both GET (generic) and  POST (generic)  is 400 Bad Request。

![企业微信截图_15565970392760](https://user-images.githubusercontent.com/36622981/56940314-1c657180-6b40-11e9-9108-5c5f33b8789f.png)

![企业微信截图_15565963204513](https://user-images.githubusercontent.com/36622981/56940316-1d969e80-6b40-11e9-8af6-495122363a80.png)

**Comment by koltyakov** [comment]
Could you try v2.8.8? I localized JSOM error, should be fixed now.

JSOM example can be found [here](https://github.com/koltyakov/sp-rest-proxy/blob/master/test/manual/static/jsom.html):

![image](https://user-images.githubusercontent.com/7816483/56944140-f08bc100-6b2a-11e9-8caa-c47c42d04dc5.png)

**Comment by rquanx** [comment]
It still doesn't work

![image](https://user-images.githubusercontent.com/36622981/56944866-a79e3180-6b57-11e9-952a-df21f3d28c90.png)

![image](https://user-images.githubusercontent.com/36622981/56944912-d1575880-6b57-11e9-9c2a-d269769914b2.png)

**Comment by koltyakov** [comment]
Can you even open a script (via `http://192.168.20.40:8110/_layouts/15/sp.js`) in a browser?

**Comment by rquanx** [comment]
Is ok

![image](https://user-images.githubusercontent.com/36622981/56945861-2052bd00-6b5b-11e9-9fa6-5ec00de5652c.png)

**Comment by koltyakov** [comment]
Weird... I can't reproduce. Checked in SPO, 2016 and 2013. Works all the time.

![image](https://user-images.githubusercontent.com/7816483/56946387-a575ac00-6b32-11e9-9b1a-a53f6b68af71.png)

Does this mean that you're accessing SP over HTTPS, but providing HTTP in proxy?

**Comment by rquanx** [comment]
It work in SPO. 
http://192.168.20.40:8110 is an intranet SP2013 website.I access it via VPN ,Is affected by this?

**Comment by koltyakov** [comment]
VPN shouldn't cause the issue. Sometimes corporate proxy can lead to a connection error. But REST requests would be blocked as well.

AAM settings might be. A rare case when IP acts as a hostname so alternative address mapping might be the case.

I'm running out of the ideas, looks like a 3rd factor which I could even repro (as mentioned above I checked this particular case with 2013 too along with SPO and 2016 environments).

As a workaround, JSOM's JavaScripts can be copied and served locally.

**Comment by rquanx** [comment]
With the v2.8.8, it works after providing JSON JavaScript locally.
I tried this method in the morning, but it didn't work at the time.
Thanks.

**Comment by koltyakov** [comment]
Going to close this one. Feel free to reopen if there are still questions.
